#!/bin/bash
#SBATCH --job-name=diann_AD_phos_search
#SBATCH --account=p20710
#SBATCH --partition=long
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=36
#SBATCH --mem=160G
#SBATCH --output=diann_AD_phos_search_%j.out
#SBATCH --error=diann_AD_phos_search_%j.err

set -Eeuo pipefail
trap 'rc=$?; echo "ERROR: command failed at line ${LINENO} with exit code ${rc}" >&2; exit "${rc}"' ERR

# Search the 16 phosphoproteomics DIA RAW files against the predicted library
# generated by Lib_Gen_Mouse_Phos_DIA-NN2.5.1_auto_corrected.sh.
#
# Submit from the project folder containing the RAWs, target FASTA, cRAP FASTA,
# and predicted library, or override WORKDIR, FASTA_DIR, LIB_DIR, and OUT_DIR.
SUBMIT_DIR="${SLURM_SUBMIT_DIR:-${PWD}}"
WORKDIR="${WORKDIR:-${SUBMIT_DIR}}"
FASTA_DIR="${FASTA_DIR:-${WORKDIR}}"
LIB_DIR="${LIB_DIR:-${WORKDIR}}"
OUT_DIR="${OUT_DIR:-${WORKDIR}}"
THREADS="${SLURM_CPUS_PER_TASK:-36}"

cd "${WORKDIR}"
mkdir -p "${OUT_DIR}"

module purge
module load diann/2.5.1-linux

RAW_FILES=(
  "${WORKDIR}/Phos_A1.raw"
  "${WORKDIR}/Phos_A2.raw"
  "${WORKDIR}/Phos_A3.raw"
  "${WORKDIR}/Phos_A4.raw"
  "${WORKDIR}/Phos_A5.raw"
  "${WORKDIR}/Phos_A6.raw"
  "${WORKDIR}/Phos_A7.raw"
  "${WORKDIR}/Phos_A8.raw"
  "${WORKDIR}/Phos_B1.raw"
  "${WORKDIR}/Phos_B2.raw"
  "${WORKDIR}/Phos_B3.raw"
  "${WORKDIR}/Phos_B4.raw"
  "${WORKDIR}/Phos_B5.raw"
  "${WORKDIR}/Phos_B6.raw"
  "${WORKDIR}/Phos_B7.raw"
  "${WORKDIR}/Phos_B8.raw"
)

# These defaults must match the library-generation script.
TARGET_FASTA_NAME="${TARGET_FASTA_NAME:-Mouse_UP000000589_2025_10_16_AD_custom_NLF_PSEN1dE9_humanMAPT.fasta}"
CONTAM_FASTA_NAME="${CONTAM_FASTA_NAME:-camprotR_240512_cRAP_20190401_full_tags.fasta}"
LIB_PREFIX="${LIB_PREFIX:-Mouse_AD_NLF_PSEN1dE9_humanMAPT_Phos}"
REPORT_PREFIX="${REPORT_PREFIX:-Human_Tau_NLF_PS1_DIA_Phos}"

# Match these values to both the predicted library and the DIA method's MS2
# isolation range. For the current DIA400-1100 workflow, the defaults are ready:
#   sbatch DIA_MS_Phos_search_DIA-NN2.5.1_auto_corrected.sh
MIN_PR_MZ="${MIN_PR_MZ:-400}"
MAX_PR_MZ="${MAX_PR_MZ:-1100}"
MIN_FR_MZ="${MIN_FR_MZ:-145}"
MAX_FR_MZ="${MAX_FR_MZ:-1450}"
MIN_PR_CHARGE="${MIN_PR_CHARGE:-2}"
MAX_PR_CHARGE="${MAX_PR_CHARGE:-3}"
MIN_PEP_LEN="${MIN_PEP_LEN:-5}"
MAX_PEP_LEN="${MAX_PEP_LEN:-30}"
MAX_VAR_MODS="${MAX_VAR_MODS:-3}"
MISSED_CLEAVAGES="${MISSED_CLEAVAGES:-1}"

LIB="${LIB_DIR}/${LIB_PREFIX}_DIA${MIN_PR_MZ}_${MAX_PR_MZ}_predict.predicted.speclib"
FASTA_MOUSE="${FASTA_DIR}/${TARGET_FASTA_NAME}"
FASTA_CONTAM="${FASTA_DIR}/${CONTAM_FASTA_NAME}"
OUT_REPORT="${OUT_DIR}/${REPORT_PREFIX}_DIA${MIN_PR_MZ}_${MAX_PR_MZ}_auto_search_report.parquet"
REPORT_STEM="${OUT_REPORT%.parquet}"

for f in "${RAW_FILES[@]}" "${LIB}" "${FASTA_MOUSE}" "${FASTA_CONTAM}"; do
  [[ -s "${f}" ]] || { echo "ERROR: missing or empty input: ${f}" >&2; exit 3; }
done

OVERWRITE="${OVERWRITE:-0}"
if [[ "${OVERWRITE}" != "0" && "${OVERWRITE}" != "1" ]]; then
  echo "ERROR: OVERWRITE must be 0 or 1; received: ${OVERWRITE}" >&2
  exit 3
fi

if [[ -e "${OUT_REPORT}" && "${OVERWRITE}" != "1" ]]; then
  echo "ERROR: output already exists: ${OUT_REPORT}" >&2
  echo "Move/delete it, or resubmit with OVERWRITE=1." >&2
  exit 3
fi

if [[ "${OVERWRITE}" == "1" ]]; then
  # Remove only files derived from this report prefix.
  rm -f -- "${REPORT_STEM}".* "${REPORT_STEM}"-*
fi

export OMP_NUM_THREADS="${THREADS}"

DIANN_RAW_ARGS=()
for raw in "${RAW_FILES[@]}"; do
  DIANN_RAW_ARGS+=(--f "${raw}")
done

echo "Host: $(hostname)"
echo "Start: $(date)"
echo "Work directory: ${WORKDIR}"
echo "FASTA directory: ${FASTA_DIR}"
echo "Library directory: ${LIB_DIR}"
echo "Output directory: ${OUT_DIR}"
echo "Threads: ${THREADS}"
echo "Raw files (${#RAW_FILES[@]}):"
printf '  %s\n' "${RAW_FILES[@]}"
echo "Library: ${LIB}"
echo "Target FASTA: ${FASTA_MOUSE}"
echo "Contaminant FASTA: ${FASTA_CONTAM}"
echo "Output: ${OUT_REPORT}"
echo "Precursor m/z range: ${MIN_PR_MZ}-${MAX_PR_MZ}"
echo "Fragment m/z range: ${MIN_FR_MZ}-${MAX_FR_MZ}"
echo "Precursor charge range: ${MIN_PR_CHARGE}-${MAX_PR_CHARGE}"
echo "DIA-NN phosphoproteomics search start: $(date)"

diann \
  "${DIANN_RAW_ARGS[@]}" \
  --lib "${LIB}" \
  --out "${OUT_REPORT}" \
  --fasta "${FASTA_CONTAM}" \
  --cont-quant-exclude cRAP- \
  --fasta "${FASTA_MOUSE}" \
  --reannotate \
  --qvalue 0.01 \
  --matrices \
  --met-excision \
  --min-pep-len "${MIN_PEP_LEN}" \
  --max-pep-len "${MAX_PEP_LEN}" \
  --min-pr-mz "${MIN_PR_MZ}" \
  --max-pr-mz "${MAX_PR_MZ}" \
  --min-fr-mz "${MIN_FR_MZ}" \
  --max-fr-mz "${MAX_FR_MZ}" \
  --min-pr-charge "${MIN_PR_CHARGE}" \
  --max-pr-charge "${MAX_PR_CHARGE}" \
  --cut 'K*,R*,!*P' \
  --missed-cleavages "${MISSED_CLEAVAGES}" \
  --unimod4 \
  --var-mods "${MAX_VAR_MODS}" \
  --var-mod 'UniMod:21,79.966331,STY' \
  --proteoforms \
  --reanalyse \
  --individual-mass-acc \
  --individual-windows \
  --matrix-spec-q 0.01 \
  --threads "${THREADS}" \
  --verbose 1

[[ -s "${OUT_REPORT}" ]] || {
  echo "ERROR: DIA-NN completed without creating the main report: ${OUT_REPORT}" >&2
  exit 4
}

ls -lh "${OUT_REPORT}"
for derived in \
  "${REPORT_STEM}.site_report.parquet" \
  "${REPORT_STEM}.stats.tsv" \
  "${REPORT_STEM}.manifest.txt"; do
  [[ ! -s "${derived}" ]] || ls -lh "${derived}"
done

echo "Completed: $(date)"
